language: nix
dist: xenial
sudo: required

before_install:
  - stty cols 80

addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - fluxbox

services:
  - xvfb

script:
  xvfb-run nix-shell --run 'make travis'
